exclude:
  - 'tests/*'
github:
  slug: leonardocouy/bambu
  access_token: <%= ENV['PRONTO_GITHUB_ACCESS_TOKEN'] %>
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
format: "%{runner} - %{msg}"
max_warnings: 150
verbose: true
